version: "3"
services:
  textile:
    image: textile/textile:latest
    restart: on-failure
    volumes:
      - "${REPO_PATH}/textile:/data/textile"
    environment:
      - TXTL_ADDR_API=/ip4/0.0.0.0/tcp/3006
      - TXTL_ADDR_API_PROXY=/ip4/0.0.0.0/tcp/3007
      - TXTL_ADDR_THREADS_HOST=/ip4/0.0.0.0/tcp/4006
      - TXTL_ADDR_GATEWAY_HOST=/ip4/0.0.0.0/tcp/8006
      - TXTL_ADDR_GATEWAY_URL
      - TXTL_ADDR_IPFS_API=/dns4/ipfs/tcp/5001
      - TXTL_EMAIL_API_KEY
      - TXTL_LOG_DEBUG
      - TXTL_LOG_FILE
    ports:
      - "127.0.0.1:3006:3006"
      - "3007:3007"
      - "4006:4006"
      - "127.0.0.1:8006:8006"
  ipfs:
    image: ipfs/go-ipfs:v0.5.0-rc2
    restart: on-failure
    volumes:
      - "${REPO_PATH}/ipfs:/data/ipfs"
    ports:
      - "4001:4001"
      - "127.0.0.1:5001:5001"
      - "8080:8080"
