version: "3"
services:
  textile:
    build:
      context: ../../
      dockerfile: ./cmd/hubd/Dockerfile
    environment:
      - HUB_LOG_DEBUG=true
      - HUB_LOG_FILE
      - HUB_ADDR_API=/ip4/0.0.0.0/tcp/3006
      - HUB_ADDR_API_PROXY=/ip4/0.0.0.0/tcp/3007
      - HUB_ADDR_MONGO_URI=mongodb://mongo:27017
      - HUB_ADDR_MONGO_NAME
      - HUB_ADDR_THREADS_HOST=/ip4/0.0.0.0/tcp/4006
      - HUB_ADDR_GATEWAY_HOST=/ip4/0.0.0.0/tcp/8006
      - HUB_ADDR_GATEWAY_URL
      - HUB_ADDR_IPFS_API=/dns4/ipfs/tcp/5001
      - HUB_ADDR_BILLING_API=billing:10006
      - HUB_ADDR_POWERGATE_API
      - HUB_GATEWAY_SUBDOMAINS
      - HUB_EMAIL_SESSION_SECRET=hubsession
      - HUB_BUCKETS_MAX_SIZE
      - HUB_THREADS_MAX_NUMBER_PER_OWNER
    ports:
      - "127.0.0.1:3006:3006"
      - "3007:3007"
      - "4006:4006"
      - "127.0.0.1:8006:8006"
  billing:
    build:
      context: ../../
      dockerfile: ./api/billingd/Dockerfile
    environment:
      - BILLING_LOG_DEBUG=true
      - BILLING_LOG_FILE
      - BILLING_ADDR_API=/ip4/0.0.0.0/tcp/10006
      - BILLING_ADDR_MONGO_URI=mongodb://mongo:27017
      - BILLING_ADDR_MONGO_NAME
      - BILLING_ADDR_GATEWAY_HOST=/ip4/0.0.0.0/tcp/8010
      - BILLING_ADDR_GATEWAY_URL
      - BILLING_STRIPE_API_KEY
      - BILLING_SEGMENT_API_KEY
      - BILLING_SEGMENT_PREFIX
    ports:
      - "127.0.0.1:10006:10006"
      - "127.0.0.1:8010:8010"
  mongo:
    image: mongo:latest
    ports:
      - "127.0.0.1:27017:27017"
  ipfs:
    image: ipfs/go-ipfs:v0.7.0
    ports:
      - "4001:4001"
      - "127.0.0.1:5001:5001"
      - "8080:8080"
