version: '3.7'

volumes:
   pow-embed-shared:

services:
  
  powergate:
    image: textile/powergate:sha-5c2ec40
    ports:
      - 8889:8889
      - 8888:8888
      - 6060:6060
      - 5002:5002
      - 6002:6002
    depends_on:
      - ipfs
      - ipfsbuckets
      - lotus
    environment:
      - POWD_EMBEDDED=true
      - POWD_LOTUSHOST=/dns4/lotus/tcp/7777
      - POWD_IPFSAPIADDR=/dns4/ipfs/tcp/5001
    volumes:
      - pow-embed-shared:/tmp/powergate
    restart: unless-stopped

  ipfs:
    image: ipfs/go-ipfs:v0.5.1

  ipfsbuckets:
    image: ipfs/go-ipfs:v0.5.1
    ports:
      - 5011:5001

  mongo:
    image: mongo:latest
    ports:
      - 27027:27017

  lotus:
    image: textile/lotus-devnet:sha-8978142
    environment:
      - TEXLOTUSDEVNET_SPEED=500
    volumes:
     - pow-embed-shared:/tmp/powergate
