version: "3"
services:
  powergate:
    image: textile/powergate:v2.0.0
    ports:
      - "8889:8889"
      - "8888:8888"
      - "6060:6060"
      - "5002:5002"
      - "6002:6002"
    depends_on:
      - ipfs
      - ipfsbuckets
      - lotus
    environment:
      - POWD_DEVNET=true
      - POWD_LOTUSHOST=/dns4/lotus/tcp/7777
      - POWD_IPFSAPIADDR=/dns4/ipfs/tcp/5001
      - POWD_FFSMINERSELECTOR=reputation
    restart: unless-stopped
  lotus:
    image: textile/lotus-devnet:v1.4.2
    environment:
      - TEXLOTUSDEVNET_SPEED=100
      - TEXLOTUSDEVNET_IPFSADDR=/dns4/ipfs/tcp/5001
      - TEXLOTUSDEVNET_BIGSECTORS=false
      - TEXLOTUSDEVNET_ONLINEMODE=${LOTUS_ONLINEMODE}
  ipfs:
    image: ipfs/go-ipfs:v0.7.0
    environment:
      - IPFS_PROFILE=local-discovery
    ports:
      - "5022:5001"
  ipfsbuckets:
    image: ipfs/go-ipfs:v0.7.0
    environment:
      - IPFS_PROFILE=local-discovery
    ports:
      - "5011:5001"
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
